services:
    _defaults:
        public: true
        autowire: true

    Ssch\TYPO3Rector\:
        resource: '../src/'
        exclude:
            - '../src/{Rector/**/*Rector.php}'
            - '../src/Console'
            - '../src/PhpStan'
            - '../src/Migrations'
    Ssch\TYPO3Rector\Migrations\Tca\TcaMigration:
        factory: ['Ssch\TYPO3Rector\Helper\TcaMigrationFactory', 'create']

